import Navbar from "../components/Navbar";
import Header from "./components/Header";
import SearchSideBar from "./components/SearchSideBar";
import RestaurantCard from "./components/RestaurantCard";
import { fetchCuisine, fetchLocation, searchRestaurantsByCity } from "../services/fetch";
import { PRICE } from "@prisma/client";

export const metadata = {
  title: "Search | OpenTable",
  description: "Generated by create next app",
};

async function Search({ searchParams }: { searchParams: { city?: string, cuisine?:string, price?:PRICE } }) {
  const search = await searchRestaurantsByCity(searchParams.city,searchParams.cuisine,searchParams.price);
  const location = await fetchLocation();
  const cuisine = await fetchCuisine();
  return (
    <>
      {/* HEADER */}
      <Header></Header>
      {/* SEARCH SIDE BAR */}
      <div className="flex py-4 m-auto w-2/3 justify-between items-start">
        <SearchSideBar location={location} cuisine={cuisine} searchParams={searchParams}></SearchSideBar>
        {/* SEARCH SIDE BAR */}
        <div className="w-5/6">
          {/* RESAURANT CAR */}
          {search.length ? (
            search.map((rest) => (
              <RestaurantCard key={rest.id} restaurant={rest} />
            ))
          ) : (
            <p>This city doens have a restaurant</p>
          )}

          {/* RESAURANT CAR */}
        </div>
      </div>
    </>
  );
}

export default Search;
